sudo: required

language: generic

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack

env:
  - STACK_YAML=stack-ghc-802.yaml
  - STACK_YAML=stack-ghc-822.yaml

jobs:
  include:
    - stage: bootstrap
      env: STACK_YAML=stack-ghc-822.yaml
      install:
      # Install Nix
      - mkdir -p ~/.nix
      - sudo mkdir -p /nix
      - sudo chmod a+w /nix
      - sudo mount --bind ~/.nix /nix
      - curl https://nixos.org/nix/install | sh
      - source ~/.nix-profile/etc/profile.d/nix.sh
      # nixpkgs-unstable not supported
      - nix-channel --add https://nixos.org/channels/nixos-17.09 nixpkgs
      - nix-channel --update
      script:
      - nix-env -i cabal-install
      - cabal update
      - nix-build nix/stackage2nix --dry-run
      - ./ci-stackage2nix --dry-run

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack --no-terminal --install-ghc build --test --haddock --no-haddock-deps --copy-bins --fast --pedantic

