resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/4e6/cabal2nix.git
    commit: 2a87207751b4f4949987c995c3962e142172312a
  extra-dep: true
extra-deps:
- distribution-nixpkgs-1.1
- hopenssl-2.2
