resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/4e6/cabal2nix.git
    commit: e57728fbc5e81ff49225f257e08b970fb9088e48
  extra-dep: true
extra-deps:
- distribution-nixpkgs-1.1
- hopenssl-2.2
