resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/4e6/cabal2nix.git
    commit: dc21f53c7b5ca36035fc369b13b43507becb80fb
  extra-dep: true
extra-deps:
- distribution-nixpkgs-1.1
- hopenssl-2.2
