resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/4e6/cabal2nix.git
    commit: 0e72390addd0a246a7a6cc8640f25b8759fd4e4e
  extra-dep: true
extra-deps:
- distribution-nixpkgs-1.1
- hopenssl-2.2
