resolver: lts-9.0
packages:
- '.'
- location:
    git: https://github.com/NixOS/cabal2nix.git
    commit: 53777ef45c45f397c1f56f9230ae494d2aefee86
  extra-dep: true
- location:
    git: https://github.com/fpco/stackage-curator.git
    commit: 3a3feeb6cc9e40bfbd7383c5e8975cd16420d822
  extra-dep: true
extra-deps:
- Cabal-2.0.0.2
nix:
  packages: [icu openssl zlib]
